### ISSUE TITLE
'path' module is there for a reason

### ISSUE THREAD

**Issue by tamerNasser** [facn6/Week5-sam-ameer-make-notes#32]
why are you adding slashes while using path.join? 
Take a look here: [](https://github.com/facn6/week4-AyaKira/issues/17#issue-472715561)
https://github.com/facn6/Week5-sam-ameer-make-notes/blob/4aa415e65c06173d3c006f169cb546aece9a7f4d/src/handlers.js#L16

**Comment by samjam48** [comment]
I fixed this.

Sorry for closing early but why are you re-opening?

**Comment by tamerNasser** [comment]
To check the merged code. I want to keep tracking for my issues.

- Issue opened 
- Assign
- Work on it
- commit with reference to the issue
- push
- PR(merge)
- Issue author checks if its fixed or still occurs
- Issue author closed the issue.
